version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./_apps/api/Dockerfile
    restart: always
    env_file:
      - ./.devcontainer/.env
    depends_on:
      - postgres
      - redis

  statemachine:
    build:
      context: .
      dockerfile: ./_apps/statemachine/Dockerfile
    restart: always
    env_file:
      - ./.devcontainer/.env
    depends_on:
      - api
  novnc:
    build:
      context: .
      dockerfile: ./_apps/novnc/Dockerfile
    restart: always
    env_file:
      - ./.devcontainer/.env
    depends_on:
      - api

  web:
    build:
      context: .
      dockerfile: ./_apps/web/Dockerfile

  postgres:
    image: postgres:latest
    restart: 'no'
    volumes:
      - postgres-data9:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 9000:5432

  redis:
    image: redis/redis-stack:latest
    restart: 'no'
    ports:
      - 9001:6379

volumes:
  postgres-data9:
